ALTER TABLE public.store_settings
  ADD COLUMN IF NOT EXISTS envia_ibscbs BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS aliq_ibsuf NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS aliq_ibsmun NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS aliq_cbs NUMERIC NOT NULL DEFAULT 0;

NOTIFY pgrst, 'reload schema';